on:
    push:
        branches:
            - main
    pull_request:


name: Clippy check

jobs:
    clippy_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Run Clippy
              run: echo "running clippy" && cargo clippy && echo "running test" && cargo test
